name: Run tests and auto-merge PR

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PyPy3.10
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.10'

    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy

    - name: Run make test
      run: make test
