name: Run tests and auto-merge PR

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up environment
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install mypy

    - name: Run make test
      run: make test

  auto-merge:
    needs: test
    runs-on: macos-latest
    if: github.event.pull_request.merged == false
  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up GitHub credentials for auto-merge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Automatically merge the PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }} --admin --body "Automatically merged after checks passed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch after merge
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/${BRANCH_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
